# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-02-17 15:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='digitalExam',
            field=models.BooleanField(default=False),
        ),
    ]
